# Generated by Django 6.0.2 on 2026-02-16 13:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_voting_active", models.BooleanField(default=False)),
                ("voting_start_date", models.DateTimeField(blank=True, null=True)),
                ("voting_end_date", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Election settings",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Automative Engineering", "Automative Engineering"),
                            ("Agriculture Extensions", "Agriculture Extensions"),
                            ("Building and Construction", "Building and Construction"),
                            ("Beauty and Hairdressing", "Beauty and Hairdressing"),
                            ("Callinery Arts", "Callinery Arts"),
                            ("Computing and Informatics", "Computing and Informatics"),
                            ("Electrical Engineering", "Electrical Engineering"),
                            ("Fashion and Design", "Fashion and Design"),
                            (
                                "Business and secretarial studies",
                                "Business and secretarial studies",
                            ),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_number", models.CharField(max_length=20, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Automative Engineering", "Automative Engineering"),
                            ("Agriculture Extensions", "Agriculture Extensions"),
                            ("Building and Construction", "Building and Construction"),
                            ("Beauty and Hairdressing", "Beauty and Hairdressing"),
                            ("Callinery Arts", "Callinery Arts"),
                            ("Computing and Informatics", "Computing and Informatics"),
                            ("Electrical Engineering", "Electrical Engineering"),
                            ("Fashion and Design", "Fashion and Design"),
                            (
                                "Business and secretarial studies",
                                "Business and secretarial studies",
                            ),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("has_voted", models.BooleanField(default=False)),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.CharField(blank=True, max_length=200)),
                ("agenda", models.TextField()),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="voting.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voting.candidate",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voting.position",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="voting.voter",
                    ),
                ),
            ],
            options={
                "unique_together": {("voter", "position")},
            },
        ),
    ]